### ISSUE TITLE
Sodium Video Settings Button Not Working

### ISSUE THREAD

**Issue by sythatic** [LimeShulkerBox/better-sodium-video-settings#41]
<pre>
[16:16:47] [Render thread/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Constructor.newInstance(Object[])" because "this.SodiumOptionsGUIClassCtor" is null
[16:16:47] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_446.flashyReesesOptionsScreen(class_446.java:570)
[16:16:47] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_446.mddbfba4$bsvsb$lambda$mixinInit$0$0(class_446.java:551)
[16:16:47] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_4185.method_25306(class_4185.java:95)
[16:16:47] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_4264.method_25348(class_4264.java:48)
[16:16:47] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_339.method_25402(class_339.java:145)
[16:16:47] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_4069.method_25402(class_4069.java:38)
[16:16:47] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_446.method_25402(class_446.java:128)
[16:16:47] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_312.method_1611(class_312.java:99)
[16:16:47] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:414)
[16:16:47] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_312.method_1601(class_312.java:99)
[16:16:47] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_312.method_22686(class_312.java:180)
[16:16:47] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:102)
[16:16:47] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_312.method_22684(class_312.java:180)
[16:16:47] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
[16:16:47] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[16:16:47] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509)
[16:16:47] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:238)
[16:16:47] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1352)
[16:16:47] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:888)
[16:16:47] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:265)
[16:16:47] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
[16:16:47] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[16:16:47] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[16:16:47] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
[16:16:47] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
[16:16:47] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
</pre>

**Comment by AshdoII** [comment]
same issue here. with reeses sodiium options and sodium extra installed. all mods are in the latest verison.

**Comment by piemanau** [comment]
What version of MC was this? And this might be fixed in the new releases of the mod.

**Comment by AshdoII** [comment]
> What version of MC was this? And this might be fixed in the new releases of the mod.

1.20.1

**Comment by SA64BD** [comment]
same. Not working

**Comment by Terraphice** [comment]
Worked on 1.20.2, doesn't work on 1.20.1.

**Comment by piemanau** [comment]
Does the latest version work?
