### ISSUE TITLE
Sodium Video Settings Button Not Working

### ISSUE THREAD

**Issue by Fierce2005** [LimeShulkerBox/better-sodium-video-settings#49]
Logs:
[20:42:27] [Render thread/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Constructor.newInstance(Object[])" because "this.SodiumOptionsGUIClassCtor" is null
[20:42:27] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.class_446.sodiumVideoOptionsScreen(class_446.java:1598)
[20:42:27] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.class_446.mdea8f4c$bsvsb$lambda$mixinInit$0$0(class_446.java:1553)
[20:42:27] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.class_4185.method_25306(class_4185.java:95)
[20:42:27] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.class_4264.method_25348(class_4264.java:48)
[20:42:27] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.class_339.method_25402(class_339.java:145)
[20:42:27] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.class_4069.method_25402(class_4069.java:38)
[20:42:27] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.class_446.method_25402(class_446.java:128)
[20:42:27] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.class_312.method_1611(class_312.java:99)
[20:42:27] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.class_437.method_25412(class_437.java:414)
[20:42:27] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.class_312.method_1601(class_312.java:99)
[20:42:27] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.class_312.method_22686(class_312.java:180)
[20:42:27] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.class_1255.execute(class_1255.java:102)
[20:42:27] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.class_312.method_22684(class_312.java:180)
[20:42:27] [Render thread/INFO]: [STDERR]: 	at knot//org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81)
[20:42:27] [Render thread/INFO]: [STDERR]: 	at knot//com.moulberry.axiom.editor.CustomImGuiImplGlfw.mouseButtonCallback(CustomImGuiImplGlfw.java:217)
[20:42:27] [Render thread/INFO]: [STDERR]: 	at knot//org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
[20:42:27] [Render thread/INFO]: [STDERR]: 	at knot//org.lwjgl.system.JNI.invokeV(Native Method)
[20:42:27] [Render thread/INFO]: [STDERR]: 	at knot//org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
[20:42:27] [Render thread/INFO]: [STDERR]: 	at knot//com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:202)
[20:42:27] [Render thread/INFO]: [STDERR]: 	at knot//com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:220)
[20:42:27] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.class_1041.method_15998(class_1041.java:287)
[20:42:27] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.class_310.method_1523(class_310.java:1349)
[20:42:27] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.class_310.method_1514(class_310.java:888)
[20:42:27] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.client.main.Main.main(Main.java:265)
[20:42:27] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
[20:42:27] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[20:42:27] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by xezoxeon** [comment]
Same here. I was going to open another issue on it but seems like the dev knows for a while now... Why would they want to code the return option? I don't blame them. they should just remove the button at that point lol 🥇

**Comment by piemanau** [comment]
I have been very busy lately unfortunately, starting my last year of school this year and last year had lots of relevant information to this year as well, so I haven't had much time to look after this project properly, unfortunately.

**Comment by xezoxeon** [comment]
> I have been very busy lately unfortunately, starting my last year of school this year and last year had lots of relevant information to this year as well, so I haven't had much time to look after this project properly, unfortunately.

That is more important for sure. Don't worry pursue your passion :)

**Comment by piemanau** [comment]
What version was this with? The alpha release on modrinth or version 3?
