### ISSUE TITLE
Incompatible with sodium extra.

### ISSUE THREAD

**Issue by MenacingPerson** [LimeShulkerBox/better-sodium-video-settings#5]
Sodium extra replaces the sodium video settings, thus causing nothing to pop up when pressing the sodium video settings button.
FlashyReese/sodium-extra-fabric#55

**Comment by piemanau** [comment]
Can I have a log please?

**Comment by MenacingPerson** [comment]
There is no crashlog, the sodium button simply does nothing. will upload a game log soon when i get home

**Comment by MenacingPerson** [comment]
Here: https://hastebin.com/ovucilucah.yaml

**Comment by piemanau** [comment]
Try downgrading a version and see if that works

**Comment by MenacingPerson** [comment]
There's only one version of sodium for 1.17, one version of BSVSB for 1.17, and one for sodium extra for 1.17. not sure what exactly you want me to do.

**Comment by piemanau** [comment]
Try downgrading BSVSB to 1.17.1 (second latest file) also update everything else first

**Comment by MenacingPerson** [comment]
i just downloaded the mods yesterday. will try downgrading

**Comment by MenacingPerson** [comment]
oh it works but it doesn't show the custom video settings.

**Comment by piemanau** [comment]
> oh it works but it doesn't show the custom video settings.

What do you mean?

**Comment by MenacingPerson** [comment]
search "reeses sodium options" which is included in sodium extra.

**Comment by piemanau** [comment]
Ah yes I know about that, I tried to fix that in my last update, if we could talk on discord that would be easier, there is a link on the description page or we can continue here let me know

**Comment by MenacingPerson** [comment]
ok i will go on discord

**Comment by MenacingPerson** [comment]
uhm where is ur discord

**Comment by MenacingPerson** [comment]
nvm found it in your other mod

**Comment by piemanau** [comment]
Alright talk to you on there!

**Comment by piemanau** [comment]
Did you join?

**Comment by MenacingPerson** [comment]
yeah

**Comment by MenacingPerson** [comment]
oh wait wrong discord

**Comment by MenacingPerson** [comment]
i dont see your discord

**Comment by piemanau** [comment]
Fixed in version 2.0.1

**Comment by Felix14-v2** [comment]
@LimeShulkerBox , it looks like it broke again in 1.18.2:

<details>
 <summary>Logs</summary>
 
[latest.log](https://github.com/LimeShulkerBox/better-sodium-video-settings/files/8238053/latest.log)

[20:32:54] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.13.3
[20:32:55] [main/WARN]: Warnings were found!
 - Mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 2.0.1+54e5b2ecd2 recommends any version of fabric-textures-v0, which is missing!
	 - You should install any version of fabric-textures-v0 for the optimal experience.
[20:32:55] [main/INFO]: Loading 18 mods:
	- bsvsb 2.0.5
	- caffeineconfig 1.0.0 via sodium-extra
	- fabric-api-base 0.4.3+d7c144a8d2 via sodium
	- fabric-key-binding-api-v1 1.0.11+54e5b2ecd2 via iris
	- fabric-lifecycle-events-v1 2.0.1+2540745460 via sodium-extra
	- fabric-rendering-data-attachment-v1 0.3.6+d7c144a8d2 via sodium
	- fabric-rendering-fluids-v1 2.0.1+54e5b2ecd2 via sodium
	- fabric-resource-loader-v0 0.4.16+55dca1a4d2 via iris
	- fabricloader 0.13.3
	- iris 1.2.1-rc2-0cc372f0-dirty
	- java 17
	- lazydfu 0.1.2
	- minecraft 1.18.2
	- org_anarres_jcpp 1.4.14 via iris
	- org_joml_joml 1.10.2 via sodium
	- reeses-sodium-options 1.4.2
	- sodium 0.4.1+build.15
	- sodium-extra 0.4.2
[20:32:55] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/%d0%90%d0%bb%d0%b5%d0%ba%d1%81%d0%b0%d0%bd%d0%b4%d1%80/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[20:32:56] [main/INFO]: Compatibility level set to JAVA_16
[20:32:56] [main/INFO]: Compatibility level set to JAVA_17
[20:32:56] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 1 override(s) found
[20:32:56] [main/INFO]: Loaded configuration file for Sodium Extra: 23 options available, 0 override(s) found
[20:32:57] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[20:32:57] [main/INFO]: Trying to switch memory allocators to work around memory leaks present with Jemalloc 5.0.0 through 5.2.0 on Windows
[20:33:11] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zzn000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[20:33:14] [Render thread/WARN]: Method overwrite conflict for method_22920 in sodium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder, previously written by net.coderbot.iris.mixin.vertices.block_rendering.MixinBufferBuilder_SeparateAo. Skipping method.
[20:33:15] [Render thread/INFO]: sodium-extra.mixins.json:gui.MinecraftClientAccessor->@Accessor[FIELD_GETTER]::getCurrentFPS()I should be static as its target is
[20:33:16] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:33:17] [Render thread/INFO]: Setting user: Felix14_v2
[20:33:18] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[20:33:20] [Render thread/WARN]: Shaders are disabled because no valid shaderpack is selected
[20:33:20] [Render thread/WARN]: Shaders are disabled
[20:33:22] [Render thread/WARN]: Hardware information:
[20:33:22] [Render thread/WARN]: CPU: 8x Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
[20:33:22] [Render thread/WARN]: GPU: NVIDIA GeForce GTX 1050/PCIe/SSE2 (Supports OpenGL 3.2.0 NVIDIA 511.79)
[20:33:22] [Render thread/WARN]: OS: Windows 10 (10.0)
[20:33:23] [Render thread/WARN]: Method overwrite conflict for getNativeMemoryUsage in sodium.mixins.json:features.debug.MixinDebugHud, previously written by net.coderbot.iris.mixin.MixinDebugScreenOverlay. Skipping method.
[20:33:23] [Render thread/INFO]: Narrator library for x64 successfully loaded
[20:33:23] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Better Sodium Video Settings Button, CaffeineConfig, Fabric API Base, Fabric Key Binding API (v1), Fabric Lifecycle Events (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Resource Loader (v0), Fabric Loader, Iris, LazyDFU, Reese's Sodium Options, Sodium, Sodium Extra)
[20:33:29] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Динамики/головные телефоны (Realtek(R) Audio)
[20:33:29] [Render thread/INFO]: Sound engine started
[20:33:30] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[20:33:30] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[20:33:30] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[20:33:30] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[20:33:30] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[20:33:30] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[20:33:30] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[20:33:35] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[20:33:35] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[20:33:35] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[20:33:46] [Render thread/INFO]: [STDERR]: java.lang.NoSuchMethodException: me.flashyreese.mods.reeses_sodium_options.client.gui.SodiumVideoOptionsScreen.<init>(net.minecraft.class_437)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.Class.getConstructor0(Class.java:3585)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.Class.getConstructor(Class.java:2271)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_446.flashyReesesOptionsScreen(class_446.java:553)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_446.mdedc889$lambda$mixinInit$0$0(class_446.java:542)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_4185.method_25306(class_4185.java:40)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_4264.method_25348(class_4264.java:16)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_339.method_25402(class_339.java:121)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_4069.method_25402(class_4069.java:27)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_446.method_25402(class_446.java:91)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_312.method_1611(class_312.java:94)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:492)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_312.method_1601(class_312.java:94)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_312.method_22686(class_312.java:165)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:103)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_312.method_22684(class_312.java:165)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1150)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:737)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:236)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[20:33:46] [Render thread/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Constructor.newInstance(Object[])" because "this.SodiumVideoOptionsScreenClassCtor" is null
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_446.flashyReesesOptionsScreen(class_446.java:560)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_446.mdedc889$lambda$mixinInit$0$0(class_446.java:542)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_4185.method_25306(class_4185.java:40)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_4264.method_25348(class_4264.java:16)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_339.method_25402(class_339.java:121)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_4069.method_25402(class_4069.java:27)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_446.method_25402(class_446.java:91)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_312.method_1611(class_312.java:94)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:492)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_312.method_1601(class_312.java:94)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_312.method_22686(class_312.java:165)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:103)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_312.method_22684(class_312.java:165)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1150)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:737)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:236)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
[20:33:46] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[20:33:48] [Render thread/INFO]: Stopping!

</details>
